sudo apt-get install gcc -y
sudo apt-get install make -y
sudo apt-get install cmake -y
sudo apt-get install pkg-config -y
sudo apt-get install libglib2.0 -y
sudo apt-get install libsdl2-dev -y
sudo apt-get install libgstreamer1.0-dev -y
sudo apt-get install libudev-dev -y
sudo apt-get install libsdl-mixer1.2-dev -y