sudo apt-get install gcc
sudo apt-get install make
sudo apt-get install cmake
sudo apt-get install pkg-config
sudo apt-get install libglib2.0
sudo apt-get install libsdl2-dev
sudo apt-get install libgstreamer1.0-dev
sudo apt-get install libsdl-mixer1.2-dev
sudo apt-get install libudev-dev